version: '3.7'

services:
  mongodb:
    container_name: tipping_bot_db
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
  tipping_bot:
    container_name: tipping_bot
    image: "tipping_bot"
    restart: "always"
    environment:
      - BISON_BANK_KEY=${DISCORD_API_KEY}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    build:
      context: .
      dockerfile: ./Dockerfile
