version: '3.7'

services:
  tipping_bot:
    container_name: tipping-bot
    image: acrdiscord.azurecr.io/tipping_bot
    restart: "always"
    environment:
      - BISON_BANK_KEY=${DISCORD_API_KEY}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    build:
      context: .
      dockerfile: ./Dockerfile
